{{- if .Values.build.enabled }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    build: {{ .Values.app_name }}
    app: {{ .Values.app_name }}
    type: 'image'
  name: {{ .Values.app_name }}
spec:
  nodeSelector:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.app_name }}:{{ .Values.build.build_tag | default "latest"}}"
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.source_docker_file_path }}
  triggers: {}
{{ end }}
