apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: repoUrl
      description: The URL of the repo to clone
    - name: repoRef
      description: The ref of the repo to clone
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
  workspaces:
  - name: source
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.repoUrl)
    - name: revision
      value: $(params.repoRef)
  - name: dockerfile-build
    runAfter:
    - git-clone
    taskRef:
      name: buildah
    params:
      - name: IMAGE
        value: "$(params.imageUrl):$(params.imageTag)"
      - name: TLSVERIFY
        value: "false"
    workspaces:
    - name: source
      workspace: source 