apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: myapp-image
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/jasee/{{ .Values.app_name }}:latest
  type: image
