apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-pipeline
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: pet-battle
  params:
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/jasee-test/pet-battle
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account
