apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: build-and-deploy-pipeline
  name: build-and-deploy-pipeline-run
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
  - name: pet-battle
    resourceRef:
      name: pet-battle-repo
  - name: image
    resourceRef:
      name: pet-battle-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
