apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  params:
    - name: repoUrl
      value: https://github.com/jacobsee/pet-battle
    - name: repoRef
      value: tekton
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/jasee-test/pet-battle
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account
